In [2]:
import numpy as np
# Hebbian Learning Rule
def hebbian_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)



In [3]:
# Perceptron Learning Rule
def perceptron_learning_rule(input_pattern, target, weight_vector, learning_rate):
    prediction = np.dot(weight_vector, input_pattern)
    error = target - prediction
    return weight_vector + learning_rate * error * input_pattern

In [4]:
 #Delta Learning Rule
def delta_learning_rule(input_pattern, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pattern)
    error = target - prediction
    return weight_matrix + learning_rate * np.outer(error, input_pattern)

# Correlation Learning Rule
def correlation_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)
# Out Star Learning Rule
def out_star_learning_rule(input_pattern, weight_matrix, learning_rate):
    return weight_matrix + learning_rate * np.outer(input_pattern, input_pattern)

In [5]:
input_size = 3
# Initialize weights with random values
hebbian_weights = np.random.rand(input_size, input_size)
perceptron_weights = np.random.rand(input_size)
delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size, input_size)
print("Hebbian Weights:",hebbian_weights)
print("\nPerceptron Weights:",perceptron_weights)
print("\nDelta Weights:",delta_weights)
print("\nCorrelation Weights:",correlation_weights)
print("\nOut Star Weights:",out_star_weights)

Hebbian Weights: [[0.37596245 0.04678533 0.26230549]
 [0.79526028 0.48060893 0.91654931]
 [0.43543927 0.39664933 0.61897153]]

Perceptron Weights: [0.27003434 0.54126361 0.90427   ]

Delta Weights: [[0.60124633 0.29557107 0.20968621]
 [0.5013131  0.1058714  0.84597156]
 [0.61747845 0.56795612 0.80536182]]

Correlation Weights: [[0.13586034 0.34368791 0.36653144]
 [0.15617941 0.44940223 0.05563218]
 [0.15389249 0.63794214 0.0293676 ]]

Out Star Weights: [[0.20431891 0.97129685 0.67929083]
 [0.26783673 0.58779989 0.44700486]
 [0.11797231 0.39548443 0.90820915]]
