In [1]:
import numpy as np

# Hebbian Learning Rule
def hebbian_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Perceptron Learning Rule
def perceptron_learning_rule(input_pattern, target, weight_vector, learning_rate):
    prediction = np.dot(weight_vector, input_pattern)
    error = target - prediction
    return weight_vector + learning_rate * error * input_pattern

# Delta Learning Rule
def delta_learning_rule(input_pattern, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pattern)
    error = target - prediction
    return weight_matrix + learning_rate * np.outer(error, input_pattern)

# Correlation Learning Rule
def correlation_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

# Out Star Learning Rule
def out_star_learning_rule(input_pattern, weight_matrix, learning_rate):
    return weight_matrix + learning_rate * np.outer(input_pattern, input_pattern)

input_size = 3
# Initialize weights with random values
hebbian_weights = np.random.rand(input_size, input_size)
perceptron_weights = np.random.rand(input_size)
delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size, input_size)

print("Hebbian Weights:",hebbian_weights)
print("\nPerceptron Weights:",perceptron_weights)
print("\nDelta Weights:",delta_weights)
print("\nCorrelation Weights:",correlation_weights)
print("\nOut Star Weights:",out_star_weights)
# Sample input and target data
input_pattern = np.array([0.2, 0.5, 0.8])
target = 1
# Apply learning rules
hebbian_weights_updated = hebbian_learning_rule(input_pattern, hebbian_weights)
perceptron_weights_updated = perceptron_learning_rule(input_pattern, target,
perceptron_weights, learning_rate=0.1)
delta_weights_updated = delta_learning_rule(input_pattern, target, delta_weights,
learning_rate=0.1)
correlation_weights_updated = correlation_learning_rule(input_pattern, correlation_weights)
out_star_weights_updated = out_star_learning_rule(input_pattern, out_star_weights,
learning_rate=0.1)

# Display updated weights
print("Hebbian Updated Weights:", hebbian_weights_updated)
print("\nPerceptron Updated Weights:", perceptron_weights_updated)
print("\nDelta Updated Weights:", delta_weights_updated)
print("\nCorrelation Updated Weights:",correlation_weights_updated)
print("\nOut Star Updated Weights:",out_star_weights_updated)

Hebbian Weights: [[0.75503452 0.71225828 0.07009069]
 [0.94219652 0.25569459 0.41946955]
 [0.35766334 0.87350969 0.68539452]]

Perceptron Weights: [0.60499501 0.79097432 0.57862784]

Delta Weights: [[0.2708325  0.62024688 0.86547984]
 [0.01603793 0.60133158 0.78977339]
 [0.97633867 0.78956219 0.33623092]]

Correlation Weights: [[0.1547905  0.86983767 0.37618916]
 [0.78821879 0.54143992 0.5079286 ]
 [0.28389837 0.55045569 0.98804701]]

Out Star Weights: [[0.93296561 0.02597775 0.16888735]
 [0.86103079 0.6728492  0.42663508]
 [0.15602174 0.76716435 0.01678979]]
Hebbian Updated Weights: [[0.79503452 0.81225828 0.23009069]
 [1.04219652 0.50569459 0.81946955]
 [0.51766334 1.27350969 1.32539452]]

Perceptron Updated Weights: [0.60540724 0.7920049  0.58027676]

Delta Updated Weights: [[0.26969902 0.61741319 0.86094594]
 [0.01732409 0.60454697 0.79491803]
 [0.979158   0.79661051 0.34750824]]

Correlation Updated Weights: [[0.1947905  0.96983767 0.53618916]
 [0.88821879 0.79143992 0.9079286 ]
 